# Generated by Django 2.2.4 on 2019-08-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='fx_rate',
        ),
    ]
